spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:develop;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      maximum-pool-size: 20
      minimum-idle: 10
      username: sa
      password:
      driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations:
        - classpath:h2/schema.sql # DB初期化用SQL
        - classpath:org/springframework/security/core/userdetails/jdbc/users.ddl # Spring-Securityによる認証用table(Users, Authorities)のセットアップschema(備え付け)
      data-locations: # 初期サンプルデータ用SQL
        - classpath:h2/data.sql
      mode: embedded # 上記SQL実行を常に行う.EMBEDDED=h2dbのとき、の意味. ALWAYSは無条件
  logging:
    level:
      org:
        springframework:
          security: DEBUG